# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 21:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reisbrein', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertravelpreferences',
            name='datetime_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usertravelpreferences',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
