# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reisbrein', '0004_auto_20171118_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertravelpreferences',
            name='likes_to_bike',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='usertravelpreferences',
            name='travel_time_importance',
            field=models.IntegerField(default=5),
        ),
    ]
