# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reisbrein', '0006_mapquestcache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapquestcache',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mapquestcache',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
