# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reisbrein', '0012_auto_20171118_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertravelplan',
            options={'ordering': ['-datetime_updated']},
        ),
        migrations.AddField(
            model_name='usertravelplan',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
