# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 20:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reisbrein', '0013_auto_20171118_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertravelplan',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
