# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reisbrein', '0016_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat', models.FloatField()),
                ('flon', models.FloatField()),
                ('tlat', models.FloatField()),
                ('tlon', models.FloatField()),
                ('transport_type', models.IntegerField()),
                ('time_sec', models.IntegerField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
