# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reisbrein', '0017_traveltime'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveltime',
            name='distance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
