# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reisbrein', '0018_traveltime_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('params', models.CharField(max_length=250)),
                ('headers', models.CharField(max_length=250)),
                ('result', models.TextField()),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MapQuestCache',
        ),
    ]
