# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reisbrein', '0019_auto_20171206_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='timedelta',
            field=models.FloatField(default=0),
        ),
    ]
