# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reisbrein', '0020_request_timedelta'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertravelpreferences',
            name='avoid_highways',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertravelpreferences',
            name='save_CO2',
            field=models.IntegerField(default=5),
        ),
    ]
