# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('title', models.CharField(max_length=500)),
                ('wandelpagina_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('wandelpagina_url', models.URLField(blank=True, max_length=500, null=True)),
                ('nswandel_url', models.URLField(blank=True, max_length=500, null=True)),
                ('begin_lon', models.FloatField()),
                ('begin_lat', models.FloatField()),
                ('end_lon', models.FloatField()),
                ('end_lat', models.FloatField()),
                ('distance', models.FloatField()),
                ('gpx', models.TextField(blank=True, default='')),
            ],
        ),
    ]
