# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wandelbrein', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trail',
            name='wandelpagina_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
